### ISSUE TITLE
Add save/load support for uppercase letters

### ISSUE THREAD

**Issue by feychou** [baphomet-berlin/ouija#14]

**Comment by cbrandolino** [comment]
I think having the possibility to change the character list in the library is enough; I would not have cases in the default editor since:
- most gridfonts are a mixture of upper- and lowercase inspired glyphs;
- the all the experiments related to the Letter Spirit project at FARG do not discriminate for cases¹;
- I don't think there's enough resolution in the default grid to create satisfactory types having both an uppercase and a lowercase letters.

¹ Come to think about it, this could be one source of confusion for the examiner/Role Model: while the fonts are namely comprised of only lowercase letters, in many instances some of the human-generated letters are strongly influenced by their uppercase version.
